name: Merge pull requests once ready

on:
  check_suite:
    types: [completed]
  pull_request_target:
    types: [labeled]
  pull_request_review:
    types: [submitted]

jobs:
  build:
    runs-on: ubuntu-latest

    name: 'Merge pull requests'

    steps:
    - name: Find pull request
      uses: fp51/actions/find-pull-request@v1
      # only useful for check_suite, we have a pull_request object on pull_request and pull_request_review
      if: github.event_name == 'check_suite'
      id: pr
      with:
        branch: ${{ github.event.check_suite.head_branch }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Merge the current pull request if possible'
      uses: fp51/actions/merge@v1
      if: >
        github.event_name != 'check_suite' || (
          github.event_name == 'check_suite'
          && github.event.check_suite.head_branch != 'main'
          && github.event.check_suite.conclusion == 'success'
          && steps.pr.outputs.pullExists == 'true'
        )
      with:
        # we use another token here
        # because an action in a workflow run can't trigger a new workflow run
        # with the GITHUB_TOKEN
        # @see https://help.github.com/en/articles/events-that-trigger-workflows#event-restrictions
        token: ${{ secrets.TOKEN_REPO_WRITE }}
        pullNumber: ${{ (github.event.pull_request_target && github.event.pull_request_target.number) || steps.pr.outputs.pullNumber }}
        label: 'Action: keep-rebased-then-merge'

